### ISSUE TITLE
fillColor is lost

### ISSUE THREAD

**Issue by sketchbook22** [ravibhojwani86/Svg2VectorAndroid#2]
Comparing to Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

if an SVG has a color defined

the result of this script always sets fill color to #FF000000

EXAMPLE:
part of SVG:
<style type="text/css">
.st0{fill:#03A9F4;}
</style>

<path class="st0" d="M24,0h0.3v40.6h-0.3z"/>

resulting part of XML:
<path android:fillColor="#FF000000"
android:pathData="M24,0h0.3v40.6h-0.3z"/>

using the converter in AndroidStudio correctly preserves the colors, how is this possible if you use the same source?

**Comment by JVilelaSmith** [comment]
I am having the same issue.

When using the jar the fillColor  is always FF000000.
I tried to run the converter manually but I get the same result, fillColor is always FF000000.
Can you provide some feedback or solution for this?

Thanks.

**Comment by ravibhojwani86** [comment]
@sketchbookgames @JVilelaSmith   Thanks for reporting and analysis. I have updated the libraries to point to latest ones and build Svg2VectorAndroid-1.0.1.jar and uploaded the same. Can you please see if it fixes the problem.
