### ISSUE TITLE
Composition Differences from Android Studio

### ISSUE THREAD

**Issue by sketchbook22** [ravibhojwani86/Svg2VectorAndroid#3]
Comparing to Android Studio 3.1.3
Build  #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

on a somewhat complex SVG with groups and clipPath and polyline
This tool results in only <path> elements
While Android Studio retains some groups, clip-paths, and strokes

The results look identical but I would prefer the results to be identical.  That is the expectation of using the same Svg2Vector source code used by Android Studio.

**one hypothesis:**

The Svg2Vector source-code you point to seems to have not changed in 3 years, could that be part of it?  Could the latest AndroidStudio use a different repo? 

https://android.googlesource.com/platform/tools/base/+/master/sdk-common/src/main/java/com/android/ide/common/vectordrawable/

**Comment by vojtaaa9** [comment]
@sketchbookgames 

Hey, today I'm facing the same issue. 

I checked out the official Android Studio Repository (branch: studio-master-dev). Now at Version 3.2.1.

I made a diff of the referenced File and the actual Svg2Vector. It is different all the way down. The new Version has about 500 more lines.
![svg2vector-diff](https://user-images.githubusercontent.com/10478901/47437394-c7b7f700-d7a8-11e8-84d6-7016d81711e8.png)

**Comment by ravibhojwani86** [comment]
@sketchbookgames @vojtaaa9  Thanks for reporting and analysis. I have updated the libraries to point to latest ones and build Svg2VectorAndroid-1.0.1.jar and uploaded the same. Can you please see if it fixes the problem.

**Comment by 1951FDG** [comment]
@ravibhojwani86 @vojtaaa9 I can confirm the latest libraries fixes the problem!

**Comment by ravibhojwani86** [comment]
Thanks for confirmation.
